name: Arduino Build

on:
  workflow_dispatch
env:
  flavor: 'sbus'
  esp32partitionsdir: '~/.arduino15/packages/esp32/hardware/esp32/2.0.11/tools/partitions'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4

    # - name: Test1
    #   working-directory: ./ps4rc
    #   run: |
    #     ls -la /home/runner/
    #     ls -la ~/.arduino15
    #     ls -la ~/.arduino15/packages/
    #     ls -la ~/.arduino15/packages/esp32/
    #     ls -la ~/.arduino15/packages/esp32/tools


    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v2
      
    - name: Test1
      working-directory: ./ps4rc
      run: |
        which arduino-cli

    - name: Install Arduino libraries
      run: |
        arduino-cli lib install EspSoftwareSerial@8.1.0 PS4Controller@1.0.8 CRC@1.0.3

    - name: Install Arduino core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32@2.0.11 --log --log-level debug

    - name: Checkout another repository
      uses: actions/checkout@v4
      with:
        repository: serg-bloim/ps4rc  # Replace with the target repository
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions automatically provides a token
        path: ps4rc  # Directory where the repo will be checked out
    
    - name: Check repo
      working-directory: ./ps4rc
      run: |
        ls -la .


    - name: Compile Arduino sketch
      working-directory: ./ps4rc
      run: |
        arduino-cli compile -e --fqbn esp32:esp32:esp32doit-devkit-v1 .

    - name: Check repo
      working-directory: ./ps4rc
      run: |
        ls -la build/esp32.esp32.esp32doit-devkit-v1

    - name: Export compiled binary
      working-directory: ./ps4rc
      run: |
        mkdir -p artifacts
        cp build/esp32.esp32.esp32doit-devkit-v1/ps4rc.ino.bootloader.bin artifacts/ps4rc_${GITHUB_REF_NAME}_${flavor}_partA_0x1000.bin
        cp build/esp32.esp32.esp32doit-devkit-v1/ps4rc.ino.partitions.bin artifacts/ps4rc_${GITHUB_REF_NAME}_${flavor}_partB_0x8000.bin
        cp ${esp32partitionsdir}/boot_app0.bin                            artifacts/ps4rc_${GITHUB_REF_NAME}_${flavor}_partC_0xE000.bin
        cp build/esp32.esp32.esp32doit-devkit-v1/ps4rc.ino.bin            artifacts/ps4rc_${GITHUB_REF_NAME}_${flavor}_partD_0x10000.bin

    - name: Upload the compiled binary as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: arduino-binary
        path: artifacts/
