name: Pull request

on: [pull_request,workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/compile.yml
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./dwld/
      - run: |
          ls -la ./dwld/
        
