name: Pull request

on: [pull_request,workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/compile.yml
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 30
      - uses: actions/download-artifact@v4
        with:
          path: dwld
      - run: |
          find .
    needs:
      - build
        
