name: Release

on: [release,workflow_dispatch]

jobs:
  build:
    uses: .github/workflows/compile.yml
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dwld
      - run: |
          find .
      - run: |
          gh release upload ${{ github.event.release.tag_name }} dwld/*
    needs:
      - build
